modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "divinebeast"
version = "1.6.53"
displayName = "Divine & Beast"
authors = "divinebeast"
description = """
闁糕晞妗ㄧ花?Curios API 闁汇劌瀚伴妶浼村传娴ｉ紦浣虹磼閸曞墎绀凢orge 1.20.1闁挎稑顦埀?
- 婵″弶鍨濈紞鍛存晬濮橀硸娈?divine) / 闁?beast)闁挎稑鑻閿嬫媴閳哄倸鐓嬮柡宥囶焾缁虹偓顨滈弶鎸庢儌闁告艾姘﹁闂佸じ鑳跺▓?12 濞戞搩浜欑紞瀣寲缂佹顐ｆ媴?- 濡ゆ婢橀幖褔鏁嶅銉㈠亾鎼达綆娈楅柕鍡楃箞閳ь剙楠搁崥鏃堝Υ韫囧海鐟?12 濞寸姵婀圭紞瀣寲婵犳哎鍋橀柛婵呯筏缁辨瑩寮捄鍝勭厺 閼? / 婵炲娲栭崹?閼?闁?- 闁靛棗娴烽〃鍥Υ韫囨梹娅忛柡瀣玻缁变即姊奸懜娈垮斀濞戞挴鍋撻悹鎰枛濞间即鏁? 濡炪倗娅㈢槐婵嬫焻閹邦亝顐介悷娆欑秮濞呭酣鏁嶆径澶岀憿闂傚棗妫濈紞鍫ュ触鎼达絾鐣遍柡浣瑰灱缁佸綊姊奸懜娈垮斀闁挎稑鐗撻ˉ锝囨偘?闁告濯介鍥╃驳婢舵稓绀塁 闂佹鍠栬ぐ鎻掝嚕閳ь剟宕楅搹顐ｆ珴閻犙冮叄閸ｆ悂鎮介悤鍌滅
- 闁哄啳娉涢崺銏☆殰閺夋寧鎯傚ù锝傛櫆閸╂捇寮崼鐔轰函闁挎稒鑹惧ú鎾淬亜鐟欏嫭娈堕柛濠傘偢濡插姊?/ 缂佸倷鑳堕弸?闁告瑥绉撮惃?/ 90% 闁稿繐绉冲┑鈧?/ 闁肩瓔鍨遍幐澶嬫櫠閻愬灚鎶勫☉鎾抽閻°劑宕?/ 婵繆顔婃鍛婂緞瀹ュ棙銇熼柨?80-缂佹稑顦辨鍥╃矓閹烘垵鏋庨柛妤勬彧缁?- 闁靛棗楠搁崥鏃堝Υ韫囨梹娅忛柡瀣玻缁辨瑦绋夋径鎰枆婵炲牏顣槐姘舵晬濮樺磭妲掗柛婊勫釜缁? 闁哄鍓濈涵鍫曞礆濞嗗繈浜奸柟璨夊棛顦伴梻鍫緛缁辨繈鏌呴幇顏咁偨閻熸瑱缍佸▍搴ㄦ晬婢跺棗鏅?闁瑰鍨遍弲鎶芥晬閸繂褰嬪ù鐘茬埣缂嶅牓鏁嶅顑跨不濡?闁告碍鐡曢、?闁稿繒鏅崗銏＄閹烘挸鐏?濞戞挸绉归妶銉︻殰婢跺摜鐟濋柟鍝勵槼閹倝鏁嶆径鍡楁櫔 闁煎浜濋崹婊堟晬閸粎顏村ù鐘烘硾閸欏繑顬囬幇鍓佺闁轰礁鐗婇悘澶婎嚗閸涘叓澶愭晬?- 婵炲娲栭崹顖涱殰閺夋寧鎯傚ù锝傛櫆閸╂捇宕＄€圭姴绠€电増顨婇埞瀣嫉瀹ュ棭鍔€闂傚牜婢佺槐?50% 濞寸鍊曢?婵炶尙鍋涢惂?闁汇垻鍠庨幊?婵烇綁鏀遍惌?闁煎浜濋崹婊堟儎?闁告氨鍋涘▍?閺夌儐鍠栧ú鏍棘閹殿喗鏅搁柨?- Curios 濞戞挸鎼ぐ鏌ユ焻婢跺﹤顤呯紓鍐惧櫙缁变即寮甸鍕殧閻熶礁鎳忓鍌炴偋閳轰焦鎯傞柣鎾楀啰鍩楅悗娑櫭﹢顏堟晬鐏炶棄娑ч柡鍕靛灡閻ュ懘寮垫径瀣擃偅鎷呭鍫滅矒闁告柣鍔嬬粭宀勫极閸喓浜?"""

# 閻犲洤鐡ㄥΣ鎴︽晬濞嗙rios 濞戞挸鎼ぐ鏌ユ焻婢跺﹤顤呯紓鍐惧櫙缁辨繃娼婚幇顖ｆ斀闁哄啫鐖奸埀顒佷亢缁诲啯绂掗敐鍥╁灣婵☆偀鍋撴繛鏉戭儜缁辨ompatChecks闁挎稑顧€缁?# 濞戞挸绉村﹢顏勵潰閵堝拋妲卞鍦濡?dependencies闁挎稑濂旀禍鎺楀礂瀹ュ洠鏁勯柣妤€鐗婂﹢浼存嚑閸愩劍绾悗浣冨閸?Forge 闁归攱甯炵划鐑藉礉閻樼儤绁伴柕?